/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DataBase.LoginManager;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;
/**
 *
 * @author Larissa Goh 18029695
 */
public class SignIn extends javax.swing.JPanel {

   private final LoginManager loginManager;

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
       loginManager = new LoginManager();
       this.setSize(600, 400); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        SignInButton = new javax.swing.JButton();
        BackToSignUpButton = new javax.swing.JButton();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        WelcomeBackLabel = new javax.swing.JLabel();
        SignInLabel = new javax.swing.JLabel();

        SignInButton.setText("Sign In");
        SignInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        BackToSignUpButton.setText("Back to Sign Up");
        BackToSignUpButton.setBorder(null);
        BackToSignUpButton.setContentAreaFilled(false);
        BackToSignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackToSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToSignUpButtonActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLabel.setText("Password");

        WelcomeBackLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WelcomeBackLabel.setText("Welcome Back!");

        SignInLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignInLabel.setText("Please Sign In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SignInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SignInButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(BackToSignUpButton)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(WelcomeBackLabel))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(WelcomeBackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignInLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackToSignUpButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        handleSignIn();
    }//GEN-LAST:event_SignInButtonActionPerformed

    private void BackToSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSignUpButtonActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.getContentPane().removeAll(); // Clear current components
        parentFrame.add(new SignUp()); // Add SignUp panel
        parentFrame.revalidate();
        parentFrame.repaint();
    }//GEN-LAST:event_BackToSignUpButtonActionPerformed
    private void handleSignIn() {
    String email = EmailField.getText().trim();
    String password = PasswordField.getText().trim();

    boolean loginSuccess = loginManager.authenticate(email, password);
    
    if (loginSuccess) {
        JOptionPane.showMessageDialog(this, "Login successful!");
        
        // Switch to Main panel
        switchToMain();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid email or password. Please try again.");
    }
}

private void switchToMain() {
    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
 // Remove current grame and add the Main panel
    mainFrame.getContentPane().removeAll();
    Main mainApp = new Main();
    mainFrame.add(mainApp.getContentPane());
    
    // Refresh the frame to display the new panel
    mainFrame.revalidate();
    mainFrame.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToSignUpButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JLabel WelcomeBackLabel;
    // End of variables declaration//GEN-END:variables
}
