/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DataBase.PlayerDB;
import Logic.SignUpHandler;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;

/**
 *
 * @author laris
 */
public class SignUp extends javax.swing.JPanel {
    
    private PlayerDB playerDB; 
    /**
     * Creates new form SignUp
     */
    public SignUp() 
    {
        initComponents();
        playerDB = new PlayerDB();
        this.setSize(600, 400); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpButton = new javax.swing.JButton();
        ExistingAccountSignInButton = new javax.swing.JButton();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        WelcometoWordleLabel = new javax.swing.JLabel();
        SignUpSignInLabel = new javax.swing.JLabel();
        FullNameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        FullNameLabel = new javax.swing.JLabel();

        SignUpButton.setText("Sign In");
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        ExistingAccountSignInButton.setText("Already signed up? Sign in here");
        ExistingAccountSignInButton.setBorder(null);
        ExistingAccountSignInButton.setContentAreaFilled(false);
        ExistingAccountSignInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExistingAccountSignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingAccountSignInButtonActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLabel.setText("Password");

        WelcometoWordleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WelcometoWordleLabel.setText("Welcome to Wordle!");

        SignUpSignInLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignUpSignInLabel.setText("Sign Up or Sign In");

        FullNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FullNameLabel.setText("Full Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SignUpButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FullNameLabel)
                                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ExistingAccountSignInButton)
                            .addComponent(WelcometoWordleLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(SignUpSignInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(WelcometoWordleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpSignInLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FullNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExistingAccountSignInButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        handleSignUp();
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ExistingAccountSignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingAccountSignInButtonActionPerformed
       JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current SignUp panel
    parentFrame.getContentPane().removeAll();

    // Add the SignIn panel to the frame
    SignIn signInPanel = new SignIn();
    parentFrame.add(signInPanel);

    // Refresh the frame to show the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
    }//GEN-LAST:event_ExistingAccountSignInButtonActionPerformed
private boolean validateInput(String fullName, String email, String password) {
        // Create an instance of SignUpHandler with the form data
        SignUpHandler signUpHandler = new SignUpHandler(fullName, email, password);

        if (!signUpHandler.validateFullName()) {  // Validate full name 
            JOptionPane.showMessageDialog(this, "Please enter your first and last name.");
            return false;
        }

        if (!signUpHandler.validateEmail()) { // Validate emaill address
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
            return false;
        }
        
        if (!signUpHandler.validatePassword()) {   // Validate password
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long.");
            return false;
        }

        return true;
    }

    private void handleSignUp() {
    // Gather form data
    String fullName = FullNameField.getText().trim();
    String email = EmailField.getText().trim();
    String password = PasswordField.getText().trim();

    // Validate input using the instance of SignUpHandler
    if (!validateInput(fullName, email, password)) {
        return; // Stop registration if validation fails
    }

    boolean success = playerDB.registerUser(fullName, email, password);

    if (success) {
        // Show success message
        JOptionPane.showMessageDialog(this, "Account succesfully made!");
        
        // Change  to SignIn panel after successful registration
        switchToSignIn();
    } else {
        JOptionPane.showMessageDialog(this, "User already exists or registration failed.");
    }
}

private void switchToSignIn() {
    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
    // Remove current grame and add the SignIn panel
    mainFrame.getContentPane().removeAll();
    SignIn signInPanel = new SignIn();
    mainFrame.add(signInPanel);
    
    // Refresh the frame to display the new panel
    mainFrame.revalidate();
    mainFrame.repaint();
}

 

//    private void openSignInWindow() {
//        // Get the parent frame that contains this panel
//        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
//        
//        // Replace the current SignUp panel with the SignIn panel
//        parentFrame.getContentPane().removeAll(); // Remove all components in the frame
//        parentFrame.add(new SignIn()); // Add the SignIn panel
//        parentFrame.revalidate(); // Revalidate to refresh the frame
//        parentFrame.repaint(); // Repaint to apply changes
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton ExistingAccountSignInButton;
    private javax.swing.JTextField FullNameField;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel SignUpSignInLabel;
    private javax.swing.JLabel WelcometoWordleLabel;
    // End of variables declaration//GEN-END:variables
}